package ms_312.CheckMeBackend.Messages;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import ms_312.CheckMeBackend.Users.User;

/**
 * Abstract class that contains the API used by platform specific classes for retrieving messages
 * from different sources.
 */
@Entity
public abstract class MessageRetriever {
    /**
     * Unique Identifier for this retriever used to store it in a database. Generated by the persistence API.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected int id;

    /**
     * A string containing the complete URL for the API endpoint to retrieve the Messages from
     */
    protected String source;

    /**
     * @param source A complete URL pointing to the API location this Retriever should get Messages from
     * @param owner The {@link User} that this reriever should get messages for
     */
    public MessageRetriever(String source, User owner) {
        this.source = source;
        this.user = owner;
    }

    /**
     * Default constructor for Persistence API
     */
    protected MessageRetriever() {}


    /**
     * The user which for which this retriever gets messages for
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    @JsonIgnore
    private User user;

    /**
     * Get all the Messages provided by the {@link MessageRetriever#source} for this Retriever
     *
     * @return An array of {@link Message} objects corresponding to all the retrieved messages.
     */
    public abstract Message[] getAll();

    /**
     * @return The {@link User} this retriever gets messages  for
     */
    public User getUser() {
        return user;
    }

    /**
     * Set the User this retriever gets messages for
     * @param user User object to set this retriever to
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * @return The numerical ID assigned to this Retriever by the persistence API
     */
    public int getId() {
        return id;
    }

    /**
     * @return The string holding the URL to the API endpoint this retriever gets messages from
     */
    public String getSource() {
        return source;
    }



}
